Repository nim-works/cps, pull requests merged in 2021-07, with the labels that each got.

#170 stack unwind in response to exceptions
  cps.nim
  cps/hooks.nim
  cps/spec.nim
  cps/transform.nim
  tests/thooks.nim
  tests/ttry.nim
Labels: enhancement

#161 More Typed AST
  cps.nim
  cps/defers.nim
  cps/environment.nim
  cps/exprs.nim
  cps/hooks.nim
  cps/normalizedast.nim
  cps/returns.nim
  cps/rewrites.nim
  cps/spec.nim
  cps/transform.nim
Labels: refactoring

#215 implements dot expression, addr, deref and magic calls flattening
  cps/exprs.nim
  cps/normalizedast.nim
  cps/spec.nim
  tests/texprs.nim
Labels: bug, release

#203 trace hook implemented as a macro
  cps.nim
  cps/hooks.nim
  cps/spec.nim
  tests/thooks.nim
Labels: enhancement, release

#220 rewrite return then annotate
  cps/environment.nim
  cps/transform.nim
  tests/treturns.nim
Labels: bug, release

#224 fix variant object field access
  cps/rewrites.nim
  tests/taste.nim
Labels: enhancement
