Repository nim-works/cps, pull requests merged in 2021-09, with the labels that each got.

#230 fixing hooks for the modern compiler
  cps/returns.nim
  cps/transform.nim
  tests/thooks.nim
Labels: release, nim compiler "feature", refactoring

#231 support borrowed cps procs; closes #226
  cps.nim
  cps/spec.nim
  tests/tapi.nim
  tests/thooks.nim
Labels: bug, release

#234 call with the continuation's type instead of the magic type
  cps/environment.nim
  cps/returns.nim
  cps/spec.nim
  tests/tapi.nim
Labels: release

#238 move path filtering to a CI job instead
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: workaround

#237 [DOC] Mention that only one debug can be enabled at a time
  README.md
Labels: documentation

#241 sink is an /optimization/; it cannot make your code more correct.
  cps/spec.nim
Labels: enhancement, merge when passing

#244 update performance test to produce same result for both tests
  stash/performance.nim
Labels: documentation, refactoring
