Repository nim-works/cps, pull requests merged in 2021-11, with the labels that each got.

#254 Fix links leading out of the repo; typos
  README.md
  docs/README.md
  tutorial/README.md
Labels: documentation

#256 add support for converting a cps call result
  cps/normalizedast.nim
  cps/spec.nim
  cps/transform.nim
  tests/treturns.nim
Labels: release

#258 allow some error-shim overloads for cpsMagic, cpsVoodoo
  README.md
  cps/spec.nim
  cps/transform.nim
  tests/tapi.nim
  tests/thooks.nim
Labels: documentation, enhancement, release
