Repository nim-works/cps, pull requests merged in 2021-06, with the labels that each got.

#168 make terminator behavior less dumb
  cps.nim
  cps/returns.nim
  cps/transform.nim
  tests/thooks.nim
  tests/tloops.nim
Labels: bug

#169 cps/transform: give the original symbol of the proc to booty
  cps/transform.nim
Labels: merge when passing, release

#196 move State and bind it for `()`
  cps.nim
  cps/environment.nim
  cps/spec.nim
  tests/tapi.nim
Labels: release
